In [8]:
#Q1)create a numpy array starting from 2 till 50 with stepsize of 3
import numpy as np

np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [8]:
#Q2)Accept two list of 5 elements each from the user.Convert them to numpy arrays.Concatenate these arrays and print itAlso sort these array and print it
import numpy as np
input_string1 = input("Enter a list elements separated by space ")
print("\n")
userList1 = input_string1.split()

input_string2 = input("Enter a list elements separated by space ")
print("\n")
userList2 = input_string2.split()  

print("user list is ", userList1,userList2)

np.concatenate((userList1, userList2), axis=0)
print("\n")
np.sort((userList1, userList2))


Enter a list elements separated by space 4 7 9 1 2


Enter a list elements separated by space 9 7 6 1 3


user list is  ['4', '7', '9', '1', '2'] ['9', '7', '6', '1', '3']




array([['1', '2', '4', '7', '9'],
       ['1', '3', '6', '7', '9']], dtype='<U1')

In [9]:
#Q3)Write a code snippet to find the dimensions of a ndarray and its size.
import numpy as np
 
a = np.array([1, 2, 5, 3])
 
# add 1 to every element
print ("Adding 1 to every element:", a+1)
 
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
 
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
 
# square each element
print ("Squaring each element:", a**2)
 
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
 
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
 
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [10]:
#Q4)How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
import numpy as np 
  
ini_array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) 
  
# printing initial arrays 
print("initial array", str(ini_array1)) 
  
# Multiplying arrays 
result = ini_array1.reshape([1, 9]) 
  
# printing result 
print("New resulting array: ", result) 

initial array [[1 2 3]
 [2 4 5]
 [1 2 3]]
New resulting array:  [[1 2 3 2 4 5 1 2 3]]


In [11]:
#Q5)Consider two square numpy arrays. Stack them vertically and horizontally.Hint: Use vstack(), hstack()

import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))
print('Vertical Append:', np.vstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


In [13]:
#Q6) How to get unique items and counts of unique items?
#importing Counter module 
from collections import Counter 

input_list = [1, 2, 2, 5, 8, 4, 4, 8] 

# creating a list with the keys 
items = Counter(input_list).keys() 
print("No of unique items in the list are:", len(items)) 


No of unique items in the list are: 5


In [ ]:
n = int(input("Enter the size of list : "))
print("\n")
numList = list(map(int, input("Enter the list numbers separated by space ").strip().split()))[:n]
print("User List: ", numList)